SPK_NAME = ffmpeg
SPK_VERS = 4.99
SPK_REV = 1
SPK_ICON = src/ffmpeg.png
CHANGELOG = "Enabled AAC codec. Disable updates to 4.1 due to bugs in HW transcoding, see https://github.com/SynoCommunity/spksrc/issues/3688"

DEPENDS = cross/$(SPK_NAME)

MAINTAINER = m4tt075, jonozzz
DESCRIPTION = FFmpeg is a complete, cross-platform solution to record, convert and stream audio and video. It includes libavcodec - the leading audio/video codec library.
DISPLAY_NAME = ffmpeg
STARTABLE = no

HOMEPAGE = http://www.ffmpeg.org/
LICENSE  = GPLv3

include ../../mk/spksrc.spk.mk
